
query PedidosBy (
  $id: ID,
  $oc: String,
  $clientesIds: [ID!]  
) {
  pedidos (
    id: $id,
    oc: $oc,
    clientesIds: $clientesIds
  ) {
    id
    cliente {
      id
      razaoSocial
    }
    fabrica {
      id
      razaoSocial
    }
    preposto {
      id
      nomeProp
    }
    situacao
    dataOrca
    dataPedi
    oc
    pediFabrica
    condicoes
    parcelas
    previEntrega
    frete
    total
    desconto
    valoComi
    porcComi
    observacao
    obsImpressao
    dataEmail
    lido
    createdAt
    createdPor
    updatedAt
    updatedPor
  }
}
