#import '@/modules/auth/graphql/UserFragment.gql'

fragment FabricaFragment on Fabrica {
  id
  situacao
  razaoSocial
  fantasia
  nomeAbrev
  email
  telefones
  criadoPor {
    ...UserFragment
  }
}
